### ISSUE TITLE
Option to throw on error in `visit`

### ISSUE THREAD

**Issue by thec0keman** [embermap/ember-cli-fastboot-testing#100]
We've found this kind of syntax useful:
```
const result = await visit('/home');

if (result.err)
  throw result.err;
```

Seems like something that could be useful to bake into the `visit` helper.

**Comment by CvX** [comment]
I like it. If an error is thrown on the backend side of ECFT, it should be re-thrown on the test frontend.

**Comment by ryanto** [comment]
Hey @thec0keman thanks for the issue.

I'd love to hear more about this idea! How are you currently using this in your tests?

**Comment by thec0keman** [comment]
Sorry for the delay in responding.

We currently are building a test suite for our fastboot conversion.  Our current plan is to take our suite of acceptance tests, and adapt a sub-set of them to also test against fastboot.

While starting this, it became clear right away that testing the DOM results could be difficult for developers since the `visit` helper always passed.  However, if we throw on an error, it makes the test perform more consistently.

This is an example test:

```
      // Network mock

      const result = await visit('/home');

      if (result.err)
        throw result.err;

      assert.exists('.nav-header');
```

**Comment by ryanto** [comment]
Interesting!

My expectation here would be that if `visit` errored here then `assert.exists('.nav-header')` would fail since fastboot wouldn't have rendered the html. Is there a case where visit errors but HTML is still rendered?

**Comment by ryanto** [comment]
Hey @thec0keman I'm going to close this issue since it might have gone stale. Feel free to reopen!
