### ISSUE TITLE
Does not work with path=dist

### ISSUE THREAD

**Issue by danwenzel** [embermap/ember-cli-fastboot-testing#144]
When running:

```
ember build --environment=test`
ember test --path=dist`
```

...fastboot tests fail with `Unexpected token C in JSON at position 0`.

This is due to the request to `__fastboot-testing` returning a 500 `Cannot read property 'visit' of undefined`, probably thrown from [this line](https://github.com/embermap/ember-cli-fastboot-testing/blob/master/index.js#L88).

I believe this is because the fastboot object is set up in the `postBuild` hook: https://github.com/embermap/ember-cli-fastboot-testing/blob/master/index.js#L158

...but `postBuild` does not run when running tests with `path=dist`

**Comment by ryanto** [comment]
Yup, looks like a bug. I guess we shouldn't assume that `postBuild` will always be run.

How about if we get to this line (https://github.com/embermap/ember-cli-fastboot-testing/blob/master/index.js#L88) and `this.fastboot` is null and `--path` is present, then we create a new server based on the path?

I'm thinking we should have a `createServer(path)` function in the addon's index that creates and sets the server.

postBuild can call `createServer(result.directory)`

And then if postBuild isn't run we can call `createServer(args.path)` if necessary.

**Comment by danwenzel** [comment]
Sounds like a good plan to me!  If I get time over the next few days, I might take a crack at it

**Comment by ryanto** [comment]
@danwenzel Try using https://github.com/substack/minimist

**Comment by danwenzel** [comment]
@ryanto - That worked perfectly!  Here you go: https://github.com/embermap/ember-cli-fastboot-testing/pull/150
