### ISSUE TITLE
Deprecation Warning in Ember 3.9+

### ISSUE THREAD

**Issue by Gaurav0** [embermap/ember-cli-fastboot-testing#198]
DEPRECATION: The <fastboot-test-app@adapter:application::ember174>#fastboot computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.

**Comment by ryanto** [comment]
Hi Gaurav,

Thanks for the report. Do you know where in this library we are overriding the fastboot computed? I can't seem to think of anything we're doing that would trigger this.

**Comment by Gaurav0** [comment]
Hi Ryan,

It is something we do that is weird in Ember Data. fastboot is a computed instead of a service. So when fastboot itself installs the service in the initializer, it overrides. We don't see this deprecation except in fastboot testing, because the order of initialization seems to be different.

Anyway, I'm making the fix in ember-data itself here: https://github.com/emberjs/data/pull/6683/files

Gaurav
