### ISSUE TITLE
FastBoot.distPath returns deleted path upon running `ember test`

### ISSUE THREAD

**Issue by dnalagatla** [embermap/ember-cli-fastboot-testing#207]
Not sure, if this is an issue with ember-cli-fastboot-testing addon but just wanted to report my observation. In my app code, in FastBoot only scenario, I am accessing the dist path using public getter  `FastBoot.distPath` to get access to a Static JSON content. 

The application works with issues upon running `ember s` and tests are passing  upon using `ember test --serve`.   But when I run just `ember test` then `FastBoot.distPath` usage failed as the path defined there is deleted.

Upon investigation, I noticed that `ember test` invokes the `postBuild` hook with broccoli temp path and deletes that path after a successful build.  As a result use of `FastBoot.distPath` fails. 

I have workaround by running `ember build` first and using the `--path` argument with `ember test`. But still wanted to check if there is any recommendation here for this use-case

**Comment by ryanto** [comment]
Interesting... I wonder if `postBuild` is not the best hook to use then? To be honest, broccoli is all a mystery to me.

I'm happy to use another hook if you think that will help. Maybe going with your work around is also the best/correct way to solve this?

**Comment by ryanto** [comment]
Ok this should be fixed in `0.2.4` thanks to @eoneill
