### ISSUE TITLE
Make this addon disable itself in prod environments

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-fastboot-testing#23]
I forget if this was related to https://github.com/embermap/ember-cli-fastboot-testing/issues/21 but we should make it so this addon disables itself in production (so it has no chance of affecting the prod build).

Here's how: https://discuss.emberjs.com/t/can-an-addon-blacklist-itself/15895/2

**Comment by ryanto** [comment]
https://github.com/embermap/ember-cli-fastboot-testing/pull/40
