### ISSUE TITLE
Allow for custom host in mockServer calls

### ISSUE THREAD

**Issue by gfmartinez** [embermap/ember-cli-fastboot-testing#310]
In our application, our api proxies to a different host, which prevents us from being able to use the mockServer to respond to the calls generated by the fastboot acceptance tests.

It would be great to just specify the hostname in the creation of a mockServer endpoint.

For example, if we are running our tests on `localhost:4200` and had `mockServer.get('htttp://localhost:3000/path/to/api', response)` then when the fastboot application test visits a page that relies on those  calls to `localhost:3000`, the mockServer can respond.

Currently, due to the way the mockServer is created via `nock`, this is impossible to do.
PR to follow shortly :)

**Comment by ryanto** [comment]
Thanks for the PR! This is released as `0.3.0`! 🎉

**Comment by gfmartinez** [comment]
@ryanto Happy to contribute! And thanks again!
