### ISSUE TITLE
Host header bug when running tests by visiting `/tests`

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-fastboot-testing#33]
![image](https://user-images.githubusercontent.com/2922250/56151195-b80eb380-5f7e-11e9-9a66-b4bdb8f298c9.png)

Believe the issue stems from the build-time environment of `development`.

Everything works if I use `ember t -s`.

**Comment by ryanto** [comment]
I think this was indirectly fixed in a later version, so if you upgrade it should go away.

Unrelated, but we also have some code that depends on build-time environment of test so thanks for pointing this out.
