### ISSUE TITLE
Add network mocking

### ISSUE THREAD

**Issue by ryanto** [embermap/ember-cli-fastboot-testing#36]
Creating an issue to track development on network mocking in fastboot-testing. Feel free to use this issue to ask and answer questions related to mocking!

PR here: https://github.com/embermap/ember-cli-fastboot-testing/pull/31

**Comment by KamiKillertO** [comment]
I was wondering if there's a way to use `ember-cli-mirage` ?
I've make some tests and it seems that mirage auto start correctly but http request make form fastboot side are not intercepted 😞

**Comment by KamiKillertO** [comment]
My bad it seems that ember-cli-mirage does not work with fastboot at all ><. Sorry for the noise

**Comment by ryanto** [comment]
Alright the first iteration of network mocking has been released in `0.0.15`!

**Comment by ryanto** [comment]
Docs here: https://embermap.github.io/ember-cli-fastboot-testing/docs/network-mocking
