### ISSUE TITLE
Do not use ember-ajax

### ISSUE THREAD

**Issue by tchak** [embermap/ember-cli-fastboot-testing#5]
Could we not use `ember-ajax` ? It is relying on jQuery being present and so will not work in apps without jQuery.

**Comment by ryanto** [comment]
Yup, more than happy to remove this.

https://github.com/embermap/ember-cli-fastboot-testing/blob/master/addon-test-support/index.js#L1

Do you know what the current best-practice way to make an ajax request in an Ember app is?

**Comment by ryanto** [comment]
I created a discuss topic related to this... https://discuss.emberjs.com/t/best-way-to-make-an-ajax-request-in-an-addon/15401

**Comment by ryanto** [comment]
All set! Published as version `0.0.3`

Let me know if you run into anything else.
