### ISSUE TITLE
Allow customizing the sandbox provided to FastBoot

### ISSUE THREAD

**Issue by ryanto** [embermap/ember-cli-fastboot-testing#57]
As a first step we can do this as a one time boot config for ECFT's FastBoot instance.

In the future it might be nice to do a per test sandbox.

**Comment by dnalagatla** [comment]
@ryanto As discussed the sandbox Globals will include basic properties in the global scope. The Basic usecase we have is to set noop for `clearInterval` and throw an error for `setInterval` in fastboot environment.  Example
```
let sanboxGlobals = {
   clearInterval: function() {
      // noop
  }
} 

const fastboot = new FastBoot({
    distPath,
    sanboxGlobal
});
```

Basically a hook during the setup which can take Globals object and passed on to the fastboot constructor  as `sandboxGlobals` property.

Thank you for looking into this task.

**Comment by ryanto** [comment]
Ok great!

I think the idea here will be to create a `config/fastboot-testing.js` file that will look something like this...

```js
module.exports = {
  sandbox: {}
};
```

**Comment by dnalagatla** [comment]
@ryanto, sorry I missed responding to the comment. That looks like a good Idea. Thank you for looking into that. I have some time right now. If you have can more detail on the generation logic, I can work on a PR for that.

**Comment by ryanto** [comment]
Hey, closing this issue since this is complete! Docs are here: https://embermap.github.io/ember-cli-fastboot-testing/docs/fastboot-configuration
