### ISSUE TITLE
Allow overriding or customization of the visit options

### ISSUE THREAD

**Issue by dnalagatla** [embermap/ember-cli-fastboot-testing#60]
Currently, visit API of fastboot is getting invoked with preset options defined in the middleware [here](https://github.com/embermap/ember-cli-fastboot-testing/blob/master/index.js#L68).

It will be useful if `visit` test helper can take custom visit options and pass it to fastboot's visit api. I think this set should per test basis.

@ryanto

**Comment by ryanto** [comment]
Absolutely agree.

To started with this do you have an examples of what you'd want to customize about `visit` in a test? Any examples would be helpful.

**Comment by dnalagatla** [comment]
> To started with this do you have an examples of what you'd want to customize about `visit` in a test? Any examples would be helpful.

So in Apps at linkedin, we don't rely on sending request object to visit API, but send `metadata` property with request context object to fastboot's visit API call. This Metadata property is included part of fastboot service used in the App code. And provide details such as A/B testing config data, and local information. The data can vary for each visit request. 

Please let me know if you need more information. thank you 😊

**Comment by dnalagatla** [comment]
Thank you @ryanto
