### ISSUE TITLE
Skip outputReady in production builds

### ISSUE THREAD

**Issue by mehulkar** [embermap/ember-cli-fastboot-testing#619]
The `outputReady` hook shouldn't need to run in production builds:
https://github.com/embermap/ember-cli-fastboot-testing/blob/441d4f9c6b5969a758ac991619b578d3c26afaf5/index.js#L49-L50

Seems implementing `isEnabled()` will do this (currently only in the `included` hook: 

https://github.com/embermap/ember-cli-fastboot-testing/blob/441d4f9c6b5969a758ac991619b578d3c26afaf5/index.js#L25-L28

--- 
The specific issue I'm running into is that `result.directory` is wrong when this hook is called (I'm trying out embroider and not yet sure if it's an issue with that or something else).

<details><summary>Details about the failure</summary>

When ember-cli calls the `outputReady` hook, the directory is correct (with my custom `--output-path`):
https://github.com/ember-cli/ember-cli/blob/26b2ee9f1b9f3431d7b96a7f850464007281eb35/lib/models/builder.js#L152

```
[ember-cli:builder] buildResults.directory /var/folders/dw/l307h_b16vzc0wys2f_nbmm00000gn/T/broccoli-121748JRezg9nx2Ji/out-1244-packager_runner_embroider_webpack
[ember-cli:builder] outputPath /dev/my-app/custom-dist-path
[ember-cli:builder] combinedOptions .directory /dev/my-app/custom-dist-path

CALLING outputReady for fb-testing with results.directory /dev/my-app/custom-dist-path
```

But inside the hook itself, it's wrong, using some default value

```
[ember-cli-fastboot-testing] process.env.EMBER_CLI_TEST_OUTPUT undefined
[ember-cli-fastboot-testing] result.directory /dev/my-app/dist <----- THIS IS WRONG
```

My only guess as to what's happening is that the object is getting updated somehow, but I'm not sure.

</details>

**Comment by ryanto** [comment]
Ah bummer, sorry you're running into this!

It sounds like doing the same `isEnabled` check in outputReady is would solve this problem? If you want to PR that I think we could merge it.

@SergeAstapov any thoughts on this?

**Comment by SergeAstapov** [comment]
@ryanto @mehulkar I think it should be safe/fine to wrap logic in the `outputReady` in the condition like we have in the `included` hook.

Sounds like it's embroider specific as didn't see any issues neither in the CI of this addon, our large app or other adding that use `ember-cli-fastboot-testing` in CI.

I'll poke around `outputReady` hook and create PR unless @mehulkar beats me.

**Comment by mehulkar** [comment]
Yep adding the same check would be ok.

**Comment by backspace** [comment]
I was having deployment problems with an Embroider application and the linked PR fixed it! 🎉 I think it’s good to merge 🤓
