### ISSUE TITLE
Cut new release v0.6.1

### ISSUE THREAD

**Issue by SergeAstapov** [embermap/ember-cli-fastboot-testing#767]
Hi @ryanto! Would you be able to cut a new release v0.6.1 with all the improvements and updates made in the past year or so?

**Comment by simonihmig** [comment]
Hey @SergeAstapov, seems you got this fixed for Ember 5! Thanks a lot for that!

Even more so a release would be appreciated! @ryanto would you be able to do that?

**Comment by gilest** [comment]
Yes, would be great to cut a new release. Believe it would be at least a minor by now.

I wonder if @ryanto could give @SergeAstapov release permissions on npm while #396 is being resolved.

Thoughts?

**Comment by SergeAstapov** [comment]
Thanks @ryanto! Got npm access, I'll work on publishing this later today.

**Comment by SergeAstapov** [comment]
@gilest @simonihmig https://github.com/embermap/ember-cli-fastboot-testing/releases/tag/v0.6.1 is now published
