### ISSUE TITLE
Add missing peerDependency `@ember/test-helpers`

### ISSUE THREAD

**Issue by mkszepp** [embermap/ember-cli-fastboot-testing#872]
The addon is shipping test-helpers, but it doesn't declare `@ember/test-helpers` as peerDependency.

https://github.com/embermap/ember-cli-fastboot-testing/blob/a0cde67aade5d68b9dadca882480d341f3e3743d/addon-test-support/index.js#L2

**Comment by SergeAstapov** [comment]
@mkszepp fixed and published as v0.6.2
